Repository IIIE-DontWorry/BE, pull requests merged in 2024-12, with the labels that each got.

#26 FEAT: 간병보고서에 배변활동 및 식사 여부 추가
  src/main/java/com/iiie/server/convertor/ConvertorDTO.java
  src/main/java/com/iiie/server/convertor/EntityUpdater.java
  src/main/java/com/iiie/server/domain/CareReport.java
  src/main/java/com/iiie/server/domain/MealExcretion.java
  src/main/java/com/iiie/server/dto/CareReportDTO.java
  src/main/java/com/iiie/server/dto/MealExcretionDTO.java
  src/main/java/com/iiie/server/service/CareReportService.java
Labels: 🎇 Feat, 💻 주혁

#27 FIX: 쪽지 API 수정 (#7)
  src/main/java/com/iiie/server/controller/NoteController.java
  src/main/java/com/iiie/server/domain/Note.java
  src/main/java/com/iiie/server/dto/NoteDTO.java
  src/main/java/com/iiie/server/repository/NoteRepository.java
  src/main/java/com/iiie/server/service/NoteService.java
Labels: 🎇 Feat, 💻 상은

#29 FEAT: 갤러리 API 구현
  src/main/java/com/iiie/server/controller/GalleryController.java
  src/main/java/com/iiie/server/dto/GalleryDTO.java
  src/main/java/com/iiie/server/service/GalleryService.java
Labels: 🎇 Feat, 💻 상은

#31 FIX: 마이페이지 조회 기능에서 http 메서드 수정
  src/main/java/com/iiie/server/controller/CaregiverController.java
  src/main/java/com/iiie/server/controller/GuardianController.java
Labels: 💻 상은, 🔧 Fix

#34 other: develop branch 최신 변경 사항 반영을 위한 병합
  build.gradle
  src/main/java/com/iiie/server/config/AwsCredentials.java
  src/main/java/com/iiie/server/config/AwsS3Config.java
  src/main/java/com/iiie/server/controller/CareReportController.java
  src/main/java/com/iiie/server/controller/CareScheduleController.java
  src/main/java/com/iiie/server/controller/CaregiverController.java
  src/main/java/com/iiie/server/controller/GalleryController.java
  src/main/java/com/iiie/server/controller/GuardianController.java
  src/main/java/com/iiie/server/controller/NoteController.java
  src/main/java/com/iiie/server/convertor/ConvertorDTO.java
  src/main/java/com/iiie/server/convertor/EntityUpdater.java
  src/main/java/com/iiie/server/domain/CareReport.java
  src/main/java/com/iiie/server/domain/Gallery.java
  src/main/java/com/iiie/server/domain/Guardian.java
  src/main/java/com/iiie/server/domain/Image.java
  src/main/java/com/iiie/server/domain/MealExcretion.java
  src/main/java/com/iiie/server/domain/Note.java
  src/main/java/com/iiie/server/domain/Patient.java
  src/main/java/com/iiie/server/dto/CareReportDTO.java
  src/main/java/com/iiie/server/dto/CareScheduleDTO.java
  src/main/java/com/iiie/server/dto/CaregiverDTO.java
  src/main/java/com/iiie/server/dto/GalleryDTO.java
  src/main/java/com/iiie/server/dto/GuardianDTO.java
  src/main/java/com/iiie/server/dto/MealExcretionDTO.java
  src/main/java/com/iiie/server/dto/NoteDTO.java
  src/main/java/com/iiie/server/repository/CareReportRepository.java
  src/main/java/com/iiie/server/repository/GalleryRepository.java
  src/main/java/com/iiie/server/repository/ImageRepository.java
  src/main/java/com/iiie/server/repository/NoteRepository.java
  src/main/java/com/iiie/server/repository/PatientRepository.java
  src/main/java/com/iiie/server/service/CareReportService.java
  src/main/java/com/iiie/server/service/CareScheduleService.java
  src/main/java/com/iiie/server/service/CaregiverService.java
  src/main/java/com/iiie/server/service/GalleryService.java
  src/main/java/com/iiie/server/service/GuardianService.java
  src/main/java/com/iiie/server/service/NoteService.java
Labels: 🎇 Feat, 💻 상은

#38 fix: duplicate key error 해결
  src/main/java/com/iiie/server/domain/Gallery.java
  src/main/java/com/iiie/server/service/GalleryService.java
Labels: 💻 상은, 🔧 Fix

#37 FEAT: 보호자 특별 요청사항 컬럼 추가
  src/main/java/com/iiie/server/controller/GuardianRequestController.java
  src/main/java/com/iiie/server/controller/UserController.java
  src/main/java/com/iiie/server/domain/CareReport.java
  src/main/java/com/iiie/server/domain/GuardianRequest.java
  src/main/java/com/iiie/server/dto/GuardianRequestDTO.java
  src/main/java/com/iiie/server/repository/GuardianRequestRepository.java
  src/main/java/com/iiie/server/service/CareReportService.java
  src/main/java/com/iiie/server/service/GuardianRequestService.java
Labels: 🎇 Feat, 💻 주혁

#40 FIX: 간병 보고서 추가 예외 task 처리
  src/main/java/com/iiie/server/domain/Gallery.java
  src/main/java/com/iiie/server/repository/CareReportRepository.java
  src/main/java/com/iiie/server/service/CareReportService.java
Labels: 💻 주혁, 🔧 Fix

#42 FEAT: 로그인 회원가입 시, ROLE도 함께 반환하도록 추가
  src/main/java/com/iiie/server/controller/UserController.java
  src/main/java/com/iiie/server/dto/UserDTO.java
  src/main/java/com/iiie/server/service/UserService.java
Labels: 🎇 Feat, 💻 주혁

#44 fix: caregiver 마이페이지 기능 수정
  src/main/java/com/iiie/server/controller/CaregiverController.java
  src/main/java/com/iiie/server/domain/CareerHistory.java
  src/main/java/com/iiie/server/domain/Patient.java
  src/main/java/com/iiie/server/dto/CaregiverDTO.java
  src/main/java/com/iiie/server/service/CaregiverService.java
Labels: 💻 상은, 🔧 Fix

#46 FEAT : GPT API로 쪽지 내용의 매너 점수 평가하여 매너점수 업데이트
  build.gradle
  src/main/java/com/iiie/server/controller/NoteController.java
  src/main/java/com/iiie/server/domain/Caregiver.java
  src/main/java/com/iiie/server/domain/Guardian.java
  src/main/java/com/iiie/server/dto/NoteDTO.java
  src/main/java/com/iiie/server/service/NoteService.java
  src/main/java/com/iiie/server/utils/NoteEvaluation.java
Labels: 🎇 Feat, 💻 상은

#47 FEAT: GitHub Actions
  .github/workflows/cicd.yml
  .gitignore
Labels: 🎇 Feat, 💻 주혁

#48 fix: 모델명, 프롬프트 수정
  src/main/java/com/iiie/server/utils/NoteEvaluation.java
Labels: 💻 상은, 🔧 Fix
